### ISSUE TITLE
Implement user authentication and get users feature for backend

### ISSUE THREAD

**Issue by nesrinejl** [nesrinejl/darna-dez-ta5tef#1]
This feature will allow user to sign up and sign in. 

**Tasks**
- [x] Create user model with different roles
- [x] Implement sign up 
- [x] Implement sign  in
- [x] Add unit and integration tests
