### ISSUE TITLE
Implement user authentication and admin dashboard layout

### ISSUE THREAD

**Issue by nesrinejl** [nesrinejl/darna-dez-ta5tef#3]
**Tasks**

- [ ] Implement sign in feature 
- [ ] Implement sign up feature
- [ ] Implement dashboard layout for admin
- [ ] Implement website layout
