### ISSUE TITLE
Implement forum, project and sponsors (backend + test)

### ISSUE THREAD

**Issue by nesrinejl** [nesrinejl/darna-dez-ta5tef#7]
**Tasks** 

- [x] Create the forum
- [x] Create comment model (schema)
- [x] Implement comment creation endpoint
- [x] Implement unit and integration tests for comment creation
- [x] Implement comment in webapp project
- [x] Implement the unit and integration test for webapp
